# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

RUN apt-get update && apt-get install -y git && apt-get clean

WORKDIR /build

RUN git clone https://github.com/gwdevhub/GuildWarsPartySearch

RUN cd GuildWarsPartySearch && \
	dotnet publish GuildWarsPartySearch/GuildWarsPartySearch.Server.csproj -c Release -r linux-x64 -o Publish && \
	cp -r GuildWarsPartySearch.FrontEnd/Content Publish/Content && \
	cp GuildWarsPartySearch/Config.Release.json Publish/Config.json

# Stage 2: Run
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build ./build/GuildWarsPartySearch/Publish .

ENTRYPOINT ["dotnet", "GuildWarsPartySearch.Server.dll"]
