FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    cmake \
    ninja-build \
    build-essential \
    git \
    clang \
    pkg-config \
    libssl-dev \
    && apt-get clean

WORKDIR /app

RUN git clone --recurse-submodules https://github.com/gwdevhub/GuildWarsPartySearch && \
    cd GuildWarsPartySearch &&\
    cmake -B build -G "Ninja" &&\
    ninja -C build

CMD ["sh", "-c", "while :; do sleep 2073600; done"]