FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    cmake \
    ninja-build \
    build-essential \
    && apt-get clean

WORKDIR /app

CMD ["sh", "-c", "while :; do sleep 2073600; done"]