services:
  nodejs-server:
    image: gwdevhub/partysearch-nodejs:latest
    pull_policy: always
    container_name: partysearch-nodejs
    ports:
      - "9095:80"
    volumes:
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
