services:
  nodejs-server:
    image: gwdevhub/partysearch-server:latest
    pull_policy: always
    container_name: partysearch-server
    ports:
      - "9095:80"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
