# Stage 1 build
FROM node:22-alpine AS build

WORKDIR /build

RUN apk update && apk add --no-cache bash

# Copies everything from local directory to /build
COPY . .

RUN npm install && npm run build

# Stage 2 Run

FROM node:22-alpine AS runtime

RUN apk update && apk add --no-cache bash

WORKDIR /app

COPY --from=build /build/ /app/

EXPOSE 80

CMD npm run serve