name: Build bot on alpine

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.20

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        apk add --no-cache \
            gcc \
            g++ \
            bash \
            cmake \
            ninja \
            ninja-build \
            python3 py3-pip py3-tqdm py3-pefile

    - name: Build
      run: |
        cd GuildWarsPartySearch.Bot
        cmake -B linuxbuild -G "Ninja"
        ninja -C linuxbuild
